import type { Metadata } from "next";
import "../styles/globals.scss";
import { Providers } from "@/providers";
import Header from "@/components/Header";
import SearchContextProvider from "@/context/searchContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <SearchContextProvider>
            <Header />
            {children}
          </SearchContextProvider>
        </Providers>
      </body>
    </html>
  );
}
